// Auto-generated TypeScript definitions for UI tree
// Generated at: 2025-12-26T00:00:00Z
// DO NOT EDIT THIS FILE MANUALLY

// ============ Base Interfaces ============

/** Widget基础接口 */
interface IWidget {
    /** 控件ID */
    readonly id: string;
    /** 控件类型 */
    readonly type: string;
    
    // Getters（同步读取）
    getText(): string;
    getVisible(): boolean;
    getEnabled(): boolean;
    getX(): number;
    getY(): number;
    getWidth(): number;
    getHeight(): number;
    
    // 便捷属性（只读）
    readonly text: string;
    readonly visible: boolean;
    readonly enabled: boolean;
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
    
    // Setters（异步命令）
    setText(text: string): void;
    setVisible(visible: boolean): void;
    setEnabled(enabled: boolean): void;
    setPosition(x: number, y: number): void;
    setSize(width: number, height: number): void;
    setColor(r: number, g: number, b: number, a: number): void;
    setProperty(property: string, value: any): void;
}

/** Button控件接口 */
interface IButton extends IWidget {
    readonly type: "button";
}

/** Label控件接口 */
interface ILabel extends IWidget {
    readonly type: "label";
}

/** TextInput控件接口 */
interface ITextInput extends IWidget {
    readonly type: "textinput";
}

/** Slider控件接口 */
interface ISlider extends IWidget {
    readonly type: "slider";
    getValue(): number;
    setValue(value: number): void;
    readonly value: number;
}

/** Image控件接口 */
interface IImage extends IWidget {
    readonly type: "image";
}

/** Panel容器接口 */
interface IPanel extends IWidget {
    readonly type: "panel";
}

// ============ Global APIs ============

/** 控制台输出 */
declare const console: {
    log(...args: any[]): void;
    error(...args: any[]): void;
};

/** 全局状态对象 */
declare const Global: {
    [key: string]: any;
};

/** Widget工具类 */
declare const Widget: {
    setProperty(widgetId: string, property: string, value: any): void;
    setText(widgetId: string, text: string): void;
    setVisible(widgetId: string, visible: boolean): void;
    setColor(widgetId: string, r: number, g: number, b: number, a: number): void;
    enable(widgetId: string): void;
    disable(widgetId: string): void;
};

/** 事件注册 */
declare function on(widgetId: string, eventName: string, handler: (event: any) => void): void;

/** 延迟执行 */
declare function setTimeout(callback: () => void, delay: number): void;

/** 定时执行 */
declare function setInterval(callback: () => void, interval: number): number;

/** 模块加载 */
declare function require(moduleName: string): any;

// ============ UI Tree Definitions ============

/** loginPanel 及其子元素 */
interface ILoginPanel extends IPanel {
    /** usernameInput子控件 */
    readonly usernameInput: ITextInput;
    /** passwordInput子控件 */
    readonly passwordInput: ITextInput;
    /** submitButton子控件 */
    readonly submitButton: IButton;
    /** errorLabel子控件 */
    readonly errorLabel: ILabel;
}

/** mainPanel 及其子元素 */
interface IMainPanel extends IPanel {
    /** welcomeLabel子控件 */
    readonly welcomeLabel: ILabel;
    /** logoutButton子控件 */
    readonly logoutButton: IButton;
    /** settingsButton子控件 */
    readonly settingsButton: IButton;
}

/** gamePanel 及其子元素 */
interface IGamePanel extends IPanel {
    /** scoreLabel子控件 */
    readonly scoreLabel: ILabel;
    /** timerLabel子控件 */
    readonly timerLabel: ILabel;
    /** pauseButton子控件 */
    readonly pauseButton: IButton;
    /** controlPanel子控件 */
    readonly controlPanel: IControlPanel;
}

/** controlPanel 及其子元素 */
interface IControlPanel extends IPanel {
    /** upButton子控件 */
    readonly upButton: IButton;
    /** downButton子控件 */
    readonly downButton: IButton;
    /** leftButton子控件 */
    readonly leftButton: IButton;
    /** rightButton子控件 */
    readonly rightButton: IButton;
}

// ============ Root Element ============

/** UI树根节点 */
interface IRootElement {
    /** loginPanel根控件 */
    readonly loginPanel: ILoginPanel;
    /** mainPanel根控件 */
    readonly mainPanel: IMainPanel;
    /** gamePanel根控件 */
    readonly gamePanel: IGamePanel;
}

/** 全局UI树根节点 */
declare const RootElement: IRootElement;
