// ============================================
// EbitenStudio UI Type Definitions
// Auto-generated by TypeScript Generator
// ============================================

// ============================================
// Base Types
// ============================================

interface BaseEvent {
    type: string;
    timestamp: number;
}

interface MouseEvent extends BaseEvent {
    x: number;
    y: number;
    button: number;
}

interface ButtonClickEvent extends MouseEvent {}
interface TextChangeEvent extends BaseEvent {
    oldText: string;
    newText: string;
}

interface KeyEvent extends BaseEvent {
    key: string;
    code: string;
    ctrlKey: boolean;
    shiftKey: boolean;
    altKey: boolean;
}

interface HoverEvent extends MouseEvent {}

// ============================================
// UI Widget Base
// ============================================

interface UIWidget {
    getID(): string;
    getType(): string;
    setVisible(visible: boolean): void;
    isVisible(): boolean;
    setEnabled(enabled: boolean): void;
    isEnabled(): boolean;
    getX(): number;
    getY(): number;
    setPosition(x: number, y: number): void;
    getWidth(): number;
    getHeight(): number;
    setSize(width: number, height: number): void;
}

// ============================================
// UI Widget Types
// ============================================

interface UIButton extends UIWidget {
    setText(text: string): void;
    getText(): string;
    setTextColor(r: number, g: number, b: number, a: number): void;
    setBackgroundColor(r: number, g: number, b: number, a: number): void;
    onClick?: (self: UIButton, event: ButtonClickEvent) => void;
    onHover?: (self: UIButton, event: HoverEvent) => void;
}

interface UILabel extends UIWidget {
    setText(text: string): void;
    getText(): string;
    setColor(r: number, g: number, b: number, a: number): void;
    setFontSize(size: number): void;
}

interface UITextInput extends UIWidget {
    setText(text: string): void;
    getText(): string;
    setPlaceholder(text: string): void;
    focus(): void;
    blur(): void;
    onChange?: (self: UITextInput, event: TextChangeEvent) => void;
    onKeyPress?: (self: UITextInput, event: KeyEvent) => void;
}

interface UIPanel extends UIWidget {
    setBackgroundColor(r: number, g: number, b: number, a: number): void;
    setBorderColor(r: number, g: number, b: number, a: number): void;
    setBorderWidth(width: number): void;
}

interface UIImage extends UIWidget {
    setImagePath(path: string): void;
    getImagePath(): string;
    setScaleMode(mode: string): void;
}

interface UICheckBox extends UIWidget {
    setChecked(checked: boolean): void;
    isChecked(): boolean;
    setLabel(text: string): void;
    onChange?: (self: UICheckBox, checked: boolean) => void;
}

interface UIRadioButton extends UIWidget {
    setChecked(checked: boolean): void;
    isChecked(): boolean;
    setGroup(group: string): void;
    getGroup(): string;
    setLabel(text: string): void;
    onChange?: (self: UIRadioButton, checked: boolean) => void;
}

interface UISlider extends UIWidget {
    setValue(value: number): void;
    getValue(): number;
    setMin(min: number): void;
    setMax(max: number): void;
    setStep(step: number): void;
    onChange?: (self: UISlider, value: number) => void;
}

interface UIComboBox extends UIWidget {
    addItem(item: string): void;
    removeItem(index: number): void;
    getSelectedIndex(): number;
    setSelectedIndex(index: number): void;
    getSelectedItem(): string;
    onChange?: (self: UIComboBox, index: number, item: string) => void;
}

interface UITableView extends UIWidget {
    setColumnCount(count: number): void;
    setRowCount(count: number): void;
    setCell(row: number, col: number, value: string): void;
    getCell(row: number, col: number): string;
    onCellClick?: (self: UITableView, row: number, col: number) => void;
}

interface UIListView extends UIWidget {
    addItem(item: string): void;
    removeItem(index: number): void;
    getSelectedIndex(): number;
    setSelectedIndex(index: number): void;
    onItemClick?: (self: UIListView, index: number, item: string) => void;
}

interface UIGridView extends UIWidget {
    setColumns(columns: number): void;
    addItem(item: string): void;
    removeItem(index: number): void;
    getSelectedIndex(): number;
    onItemClick?: (self: UIGridView, index: number) => void;
}

// ============================================
// Global APIs
// ============================================

interface Console {
    log(...args: any[]): void;
    error(...args: any[]): void;
    warn(...args: any[]): void;
    info(...args: any[]): void;
}

interface Global {
    setTimeout(callback: () => void, delay: number): number;
    clearTimeout(id: number): void;
    setInterval(callback: () => void, delay: number): number;
    clearInterval(id: number): void;
}

declare const console: Console;
declare const Global: Global;

// ============================================
// RootElement - Dynamic UI Access
// ============================================

interface RootElement {
    getElementById(id: string): UIWidget | null;
    getByType(type: string): UIWidget[];
    
    // Example dynamic properties (customize based on your UI):
    // mainPanel?: UIPanel;
    // loginButton?: UIButton;
    // usernameInput?: UITextInput;
}

declare const RootElement: RootElement;
